-- Insert sample data into the VoteAnswer table with counts set to 0 and UserId set to NULL
INSERT INTO VoteAnswers (OptionText, VoteId, VotesCount, UserId)
VALUES
    ('Community Garden Expansion', 1, 0, NULL),
    ('Youth Mentorship Program', 1, 0, NULL),
    ('Park Renovation Project', 1, 0, NULL),
    ('Senior Citizens'' Center Upgrades', 1, 0, NULL),
    ('Arts and Culture Festival', 1, 0, NULL),
    ('Sports Facility Improvements', 1, 0, NULL),
    ('Environmental Cleanup Initiative', 1, 0, NULL),
    ('After-School Program Expansion', 1, 0, NULL),
    ('Regularly', 2, 0, NULL),
    ('Occasionally', 2, 0, NULL),
    ('Rarely', 2, 0, NULL),
    ('Never', 2, 0, NULL),
    ('I''m actively involved in multiple community projects!', 2, 0, NULL),
    ('Enhancing Quality of Life', 3, 0, NULL),
    ('Strengthening Community Bonds', 3, 0, NULL),
    ('Environmental Conservation', 3, 0, NULL),
    ('Supporting Youth Development', 3, 0, NULL),
    ('Cultural Enrichment', 3, 0, NULL),
    ('Health and Wellness', 3, 0, NULL),
    ('Economic Growth', 3, 0, NULL),
    ('I support all these reasons!', 3, 0, NULL),
    ('Education', 4, 0, NULL),
    ('Healthcare', 4, 0, NULL),
    ('Public Spaces', 4, 0, NULL),
    ('Employment Opportunities', 4, 0, NULL),
    ('Social Services', 4, 0, NULL),
    ('Environment', 4, 0, NULL),
    ('Safety and Security', 4, 0, NULL),
    ('All of the above', 4, 0, NULL),
    ('Neighborhood Watch', 5, 0, NULL),
    ('Environmental Advocates Group', 5, 0, NULL),
    ('Youth Sports League', 5, 0, NULL),
    ('Cultural Arts Society', 5, 0, NULL),
    ('Food Bank and Shelter', 5, 0, NULL),
    ('Senior Citizens'' Association', 5, 0, NULL),
    ('Education Foundation', 5, 0, NULL);
